# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pympp',
                'doc_host': 'https://joLahann.github.io',
                'git_url': 'https://github.com/joLahann/pympp',
                'lib_path': 'pympp'},
  'syms': {'pympp.core': {'pympp.core.foo': ('core.html#foo', 'pympp/core.py')}}}
