project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating
    contents:
      - "index.ipynb"
      - "00_logs.ipynb"
      - "01_process.ipynb"
      - section: Prediction
        contents: "*prediction*.ipynb"
      - section: Anomaly Detection
        contents: "*anomaly*.ipynb"

metadata-files: [nbdev.yml]
